### ISSUE TITLE
Create tests for the Python solutions

### ISSUE THREAD

**Issue by lnxpy** [saadfareed/Leetcode#79]
I dived through your Python directory structure and noticed that you're using a pure static structure for keeping the algorithm files. You can have a directory per each algorithm and keep an introduction to the algorithm as well as its tests alongside the script.

```
python/
├── binary_search/
│   ├── intro.md
│   ├── algorithm.py
│   └── test.py
├── queue/
│   ├── intro.md
│   ├── algorithm.py
│   └── test.py
└── ...
```

I can work on it btw.

**Comment by saadfareed** [comment]
It would be amazing
